version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fatma
      POSTGRES_PASSWORD: fatam
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
